/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as recoverySol from "./Recovery.sol";
export type { recoverySol };
export type { Account } from "./Account";
