/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWithOwners__factory } from "./IWithOwners__factory";
export { Recovery__factory } from "./Recovery__factory";
